### Archivos .sav (SPSS) con Pandas

In [2]:
import pandas as pd
import pyreadstat

df, meta = pyreadstat.read_sav('./CIS/MD3263_macrobarometro_19/3263.sav')

In [3]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df

,ESTU,CUES,CCAA,PROV,MUN,TAMUNI,CAPITAL,DISTR,SECCION,ENTREV,...,VOTOSIMG,P9BR,P13R,P14R,P15R,P17AR,RECUERDO,ESTUDIOS,PESO,PESOCCAA
0,3263.0,1.0,16.0,1.0,59.0,5.0,1.0,0.0,0.0,0.0,...,2.0,NaN,2.0,98.0,2.0,2.0,2.0,3.0,0.52587,0.5208
1,3263.0,2.0,16.0,1.0,59.0,5.0,1.0,0.0,0.0,0.0,...,98.0,NaN,12.0,2.0,21.0,12.0,12.0,6.0,0.52587,0.5208
2,3263.0,3.0,16.0,1.0,59.0,5.0,1.0,0.0,0.0,0.0,...,1.0,97.0,1.0,2.0,99.0,NaN,97.0,2.0,0.52587,0.5208
3,3263.0,4.0,16.0,1.0,59.0,5.0,1.0,0.0,0.0,0.0,...,96.0,NaN,97.0,98.0,98.0,99.0,99.0,6.0,0.52587,0.5208
4,3263.0,5.0,16.0,1.0,59.0,5.0,1.0,0.0,0.0,0.0,...,99.0,NaN,21.0,2.0,12.0,99.0,99.0,6.0,0.52587,0.5208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17645,3263.0,18005.0,13.0,28.0,79.0,7.0,1.0,0.0,0.0,0.0,...,18.0,97.0,18.0,95.0,18.0,18.0,18.0,4.0,3.34223,1.0000
17646,3263.0,18006.0,13.0,28.0,79.0,7.0,1.0,0.0,0.0,0.0,...,21.0,21.0,5.0,2.0,21.0,2.0,2.0,3.0,3.34223,1.0000
17647,3263.0,18007.0,13.0,28.0,79.0,7.0,1.0,0.0,0.0,0.0,...,21.0,77.0,21.0,2.0,21.0,21.0,21.0,5.0,3.34223,1.0000
17648,3263.0,18008.0,13.0,28.0,79.0,7.0,1.0,0.0,0.0,0.0,...,97.0,NaN,4.0,98.0,4.0,4.0,4.0,4.0,3.34223,1.0000
17649,3263.0,18009.0,13.0,28.0,79.0,7.0,1.0,0.0,0.0,0.0,...,4.0,NaN,4.0,2.0,4.0,4.0,4.0,6.0,3.34223,1.0000